// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import config from "./src/config/config.js";

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource : {
    url:config.DATABSE_URI,
  },
});
